

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8008:8008"
    volumes:
      - ./backend:/app
      - ./backend/my_media:/files/media
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate && 
            python manage.py runserver 0.0.0.0:8008"
    depends_on:
      - db

#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./frontend:/app
#    command: >
#      sh -c "npm install && npm start"
#    depends_on:
#      - backend

  db:
    image: postgres:16.2-alpine3.19
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - my_db:/var/lib/postgresql/data

volumes:
  my_db:
  my_media:
